"""update camera nullable fields

Revision ID: 21e510ef4c94
Revises: 4b0fb502d0f1
Create Date: 2025-10-30 10:29:07.864367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e510ef4c94'
down_revision = '4b0fb502d0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.alter_column('rtsp_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.alter_column('rtsp_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
